### PR TITLE
Feature/database transition

### PR DESCRIPTION
**Pull request by Myrelin**
Frontend wasn't able to map single-movie view for searches once reviews were added;
search endpoint now returns a list of movies (containing a single movie) same as the index.

(frontend code also altered to reflect this).

### CODE REVIEW

**Review by thaoPhLam — APPROVED** [review]
Anna, you are a fighter! An avenger! :muscle:

**Comment by Myrelin** [comment]
@thaoPhLam We are ALL Avengers on this glorious day!

**Review by istvanZsolnai — APPROVED** [review]
should have some rest sometimes

**Comment by Myrelin** [comment]
@istvanZsolnai SLEEP IS FOR THE WEAK! ...And for the tired. :sleeping:

**Pull request merged**
